export const SubscriberExample = {
  Count: 2,
  Data: [
    {
      SystemId: null,
      Area: '',
      PublicId: 161,
      CountryCode: 'CO',
      CountryName: 'Colombia',
      Name: 'prueba',
      Email: 'carlosurrego82@gmail.com',
      JobTitle: '',
      PhoneNumber: '3148654325',
      PhoneCode: '57',
      PhoneCodeAndNumber: '(57) 3148654325',
      LastActivityUtc: null,
      LastActivity: null,
      SubscriptionDate: null,
      SubscriptionMethod: 0,
      SubscriptionState: 0,
      SubscriptionStateDescription: 'Pendiente',
      Topics: [],
      Activity: '--',
      ConnectionState: 2,
      Id: 7914,
    },
    {
      SystemId: null,
      Area: 'Desarrollo',
      PublicId: 162,
      CountryCode: 'CO',
      CountryName: 'Colombia',
      Name: 'Carlos Urrego',
      Email: 'carlos.urrego@tekus.co',
      JobTitle: 'QA',
      PhoneNumber: '3102001350',
      PhoneCode: '57',
      PhoneCodeAndNumber: '(57) 3102001350',
      LastActivityUtc: '2021-02-27T01:41:24.377',
      LastActivity: '2021-02-26T20:41:24.377',
      SubscriptionDate: '22/02/2021 4:36 p. m.',
      SubscriptionMethod: 0,
      SubscriptionState: 1,
      SubscriptionStateDescription: 'Activo',
      Topics: [],
      Activity: '5d 15h ',
      ConnectionState: 2,
      Id: 7927,
    },
    {
      "SystemId": null,
      "Area": "Ventas",
      "PublicId": 163,
      "CountryCode": "MX",
      "CountryName": "México",
      "Name": "Juan Pérez",
      "Email": "juan.perez@example.com",
      "JobTitle": "Ejecutivo de Ventas",
      "PhoneNumber": "1234567890",
      "PhoneCode": "52",
      "PhoneCodeAndNumber": "+52 1234567890",
      "LastActivityUtc": "2022-06-10T00:00:00.000Z",
      "LastActivity": "2022-06-09T19:00:00.000Z",
      "SubscriptionDate": "10/05/2022",
      "SubscriptionMethod": 0,
      "SubscriptionState": 1,
      "SubscriptionStateDescription": "Activo",
      "Topics": [],
      "Activity": "5d 15h",
      "ConnectionState": 2,
      "Id": 7928
    },
    {
      "SystemId": null,
      "Area": "Marketing",
      "PublicId": 164,
      "CountryCode": "ES",
      "CountryName": "España",
      "Name": "Ana López",
      "Email": "ana.lopez@example.com",
      "JobTitle": "Especialista en Marketing Digital",
      "PhoneNumber": "987654321",
      "PhoneCode": "34",
      "PhoneCodeAndNumber": "+34 987654321",
      "LastActivityUtc": "2022-07-15T00:00:00.000Z",
      "LastActivity": "2022-07-14T19:00:00.000Z",
      "SubscriptionDate": "15/07/2022",
      "SubscriptionMethod": 0,
      "SubscriptionState": 1,
      "SubscriptionStateDescription": "Activo",
      "Topics": [],
      "Activity": "5d 15h",
      "ConnectionState": 2,
      "Id": 7929
    },
    {
      "SystemId": null,
      "Area": "Desarrollo",
      "PublicId": 165,
      "CountryCode": "US",
      "CountryName": "Estados Unidos",
      "Name": "David Smith",
      "Email": "david.smith@example.com",
      "JobTitle": "Desarrollador Frontend",
      "PhoneNumber": "9876543210",
      "PhoneCode": "1",
      "PhoneCodeAndNumber": "+1 9876543210",
      "LastActivityUtc": "2022-09-20T00:00:00.000Z",
      "LastActivity": "2022-09-19T19:00:00.000Z",
      "SubscriptionDate": "20/09/2022",
      "SubscriptionMethod": 0,
      "SubscriptionState": 1,
      "SubscriptionStateDescription": "Activo",
      "Topics": [],
      "Activity": "5d 15h",
      "ConnectionState": 2,
      "Id": 7930
    },
    {
      "SystemId": null,
      "Area": "Recursos Humanos",
      "PublicId": 166,
      "CountryCode": "AR",
      "CountryName": "Argentina",
      "Name": "Maria García",
      "Email": "maria.garcia@example.com",
      "JobTitle": "Gerente de Recursos Humanos",
      "PhoneNumber": "987654321",
      "PhoneCode": "54",
      "PhoneCodeAndNumber": "+54 987654321",
      "LastActivityUtc": "2022-11-05T00:00:00.000Z",
      "LastActivity": "2022-11-04T19:00:00.000Z",
      "SubscriptionDate": "05/11/2022",
      "SubscriptionMethod": 0,
      "SubscriptionState": 1,
      "SubscriptionStateDescription": "Activo",
      "Topics": [],
      "Activity": "5d 15h",
      "ConnectionState": 2,
      "Id": 7931
    },
    {
      "SystemId": null,
      "Area": "Finanzas",
      "PublicId": 167,
      "CountryCode": "CA",
      "CountryName": "Canadá",
      "Name": "Robert Johnson",
      "Email": "robert.johnson@example.com",
      "JobTitle": "Analista Financiero",
      "PhoneNumber": "1234567890",
      "PhoneCode": "1",
      "PhoneCodeAndNumber": "+1 1234567890",
      "LastActivityUtc": "2022-12-30T00:00:00.000Z",
      "LastActivity": "2022-12-29T19:00:00.000Z",
      "SubscriptionDate": "30/12/2022",
      "SubscriptionMethod": 0,
      "SubscriptionState": 1,
      "SubscriptionStateDescription": "Activo",
      "Topics": [],
      "Activity": "5d 15h",
      "ConnectionState": 2,
      "Id": 7932
    },
  ],
};

export const CountryExample = {
  Count: 255,
  Data: [
    {
      Code: 'ZW',
      Name: 'Zimbabwe',
      PhoneCode: '263 ',
    },
    {
      Code: 'ZM',
      Name: 'Zambia',
      PhoneCode: '260 ',
    },
    {
      Code: 'ZA',
      Name: 'South Africa',
      PhoneCode: '27 ',
    },
    {
      Code: 'YT',
      Name: 'Mayotte',
      PhoneCode: '269 ',
    },
    {
      Code: 'YE',
      Name: 'Yemen',
      PhoneCode: '967 ',
    },
    {
      Code: 'XK',
      Name: 'Kosovo',
      PhoneCode: null,
    },
    {
      Code: 'WS',
      Name: 'Samoa',
      PhoneCode: '684 ',
    },
    {
      Code: 'WF',
      Name: 'Wallis & Futuna',
      PhoneCode: '681 ',
    },
    {
      Code: 'VU',
      Name: 'Vanuatu',
      PhoneCode: '678 ',
    },
    {
      Code: 'VN',
      Name: 'Vietnam',
      PhoneCode: '84 ',
    },
  ],
};
